import React from "react";
import Navbar from "@/components/navigation/navbar";
import { getCurrentSession } from "@/auth/cookies";
import { redirect } from "next/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets : ['latin'] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getCurrentSession();
  if (session === null) {
    return redirect("/login");
  }

  return (
    <html lang="en">
    <body
      className={`${inter.className} antialiased`}
    >
    <section>
      <Navbar user={user}/>
    </section>
    <main>{children}</main>
    </body>
    </html>
  )
}